/**
 * @bfrost/manifest-schema
 *
 * Canonical enum types for BFrost worker manifests.
 *
 * This is the single source of truth for TrustLevel, WorkerCategory, and
 * WorkerPermission. BFrost, BFrost-Website, and BFrost-Workers all depend
 * on this package. Adding or removing an enum value is a one-line change
 * here that propagates to all consumers via TypeScript and CI checks.
 *
 * AUTO-GENERATED by scripts/generate-enums.js in BFrost-Workers.
 * Source: schema.json → packages/manifest-schema/src/index.ts
 * Run `npm run generate:enums` in BFrost-Workers to regenerate.
 */

// ---------------------------------------------------------------------------
// Trust Levels
// ---------------------------------------------------------------------------

export type TrustLevel =
  | 'Trusted'
  | 'Verified'
  | 'Community'
  | 'Review'
  | 'Core';

export const TRUST_LEVELS: TrustLevel[] = [
  'Trusted',
  'Verified',
  'Community',
  'Review',
  'Core',
];

// ---------------------------------------------------------------------------
// Worker Categories
// ---------------------------------------------------------------------------

export type WorkerCategory =
  | 'AI / Research'
  | 'Communication'
  | 'Productivity'
  | 'AI / Inference'
  | 'Developer Tools'
  | 'Backup'
  | 'Core / Channel'
  | 'Core / Provider'
  | 'Core / Plugin'
  | 'Core / Tool';

export const WORKER_CATEGORIES: WorkerCategory[] = [
  'AI / Research',
  'Communication',
  'Productivity',
  'AI / Inference',
  'Developer Tools',
  'Backup',
  'Core / Channel',
  'Core / Provider',
  'Core / Plugin',
  'Core / Tool',
];

// ---------------------------------------------------------------------------
// Worker Permissions (store-level, high-level categories)
// ---------------------------------------------------------------------------

export type WorkerPermission =
  | 'network:http'
  | 'network:https'
  | 'storage:worker-kv'
  | 'filesystem:scoped-read'
  | 'filesystem:scoped-write'
  | 'filesystem:workspace-read'
  | 'operator-notify'
  | 'local-process';

export const WORKER_PERMISSIONS: WorkerPermission[] = [
  'network:http',
  'network:https',
  'storage:worker-kv',
  'filesystem:scoped-read',
  'filesystem:scoped-write',
  'filesystem:workspace-read',
  'operator-notify',
  'local-process',
];
